config/routes.rb
Rails.application.routes.draw do
  resources :games
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'games#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :chat_messages, only: [:create]
  get '/chat_messages/' => 'chat_messages#index'

end

app/models/chat_message.rb
class ChatMessage
	include ActiveModel::Model
  attr_accessor :name, :message, :id
end

app/models/game.rb
class Game < ActiveRecord::Base
	attr_accessor :gameID, :num_of_players, :max_players
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  
  def index
    @chat_message = ChatMessage.new
  end

  def show
    @chat_message = ChatMessage.new
  end

  def create
  	@chat_message = ChatMessage.new(params[:chat_message])
    @chat_message.name = current_user.email
    channel = params[:channel]
    Pusher.trigger(channel, 'new_message', {
      name: @chat_message.name,
      message: @chat_message.message }, 
      {
        socket_id: params[:socket_id], 
      })

    respond_to :js
  end

  def trigger(channel)
    # # channel << params[:id]
    # Pusher.trigger(channel, 'new_message', {
    #   name: @chat_message.name,
    #   message: @chat_message.message }, 
    #   {
    #     socket_id: params[:socket_id],
    #     id: params[:id]
    #   })

    # respond_to :js
  end
end

###################
# what i did
# able to make multiple chat channels based on id
# need to figure out
# trigger to the game room specific chat channel

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  attr_accessor :id
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    @chat_message = ChatMessage.new
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @chat_message = ChatMessage.new
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
        @id = format.json {render :id}
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params[:game]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	Pusher['test_channel'].trigger('greet', {
  :greeting => "Hello there!"
})
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pusher_include_tag(version)
    domain = if request.ssl?
      'https://d3dy5gmtp8yhk7.cloudfront.net'
    else
      'http://js.pusher.com'
    end
    javascript_include_tag "#{domain}/#{version}/pusher.min.js"
  end
end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chat_messages/_chat_message.html.erb
<%= chat_message.name %>: <%= chat_message.message %><br>

app/views/chat_messages/_index.html.erb
<!DOCTYPE html>
<html>
<head>
  <script>
</script>
</head>
<body>
<div id="chat"><%= game_id %></div>
<%= form_for chat_message, remote: true do |f| %>
  <div style="display:none">
    <%= hidden_field_tag :socket_id %>
    <%= hidden_field_tag :channel, game_id %>
  </div>
  <div class="chat_messages"></div>
  <br><br>
  <div>
    <%= f.label :message %>
    <%= f.text_field :message, :size=> "50", placeholder: "Hit enter to send" %>
  </div>
<% end %>
</body>
</html>

app/views/chat_messages/create.js.erb
//alert('<%= @chat_message.name %> says <%= @chat_message.message %>');
// clear the message box
$('#chat_message_message').val('');

// show the message in the messages area
$('.chat_messages').append('<%= escape_javascript(render @chat_message) %>');

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<head>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script src="http://js.pusher.com/2.0/pusher.min.js"></script>
  </head>
  <body>
<p id="notice"><%= notice %></p>

<div class="game-block">
<h1>Lobby</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <div class="list-of-games">
    <% @games.each do |game| %>
      <tr>
        <td>Game Room #<%= game.id %></td>
        <td>  Number of players: 0<!--insert num_of_players dynamically later -->/8</td>
        <td><%= link_to 'Show', game %></td>

        <!-- <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
</table>


<br>

<!--<%= link_to 'New Game', new_game_path %> -->

</div>
</div>

<div class="chat-block">
Global Chat
<%= render :partial => 'chat_messages/index', :locals =>{:chat_message => @chat_message, :game_id => '0'} %>
</div>
<%= pusher_include_tag '2.2' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<head>
	<script>
	</script>
</head>
<body>
<p id="notice"><%= notice %></p>
<div class="chat-block">
Game Chat
<%= render :partial => 'chat_messages/index', :locals =>{:chat_message => @chat_message, :game_id => params[:id]} %>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MafiaTown</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

</head>
<body>

<%= yield %>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<meta charset="UTF-8">

<title>Mafia</title>

<link rel="stylesheet" type="text/css">

<script src="//js.pusher.com/2.2/pusher.min.js"></script>
<script>
// If your Heroku application is within the EU region,
// uncomment the followling lines
// Pusher.host = 'ws-eu.pusher.com';
// Pusher.sockjs_host = 'sockjs-eu.pusher.com';

var pusher = new Pusher('<%= Pusher.key %>'); // uses your APP KEY
var channel = pusher.subscribe('test_channel');
channel.bind('greet', function(data) {
  alert(data.greeting);
});
</script>

</head>

<body>

<a href="login.html"><div class="logo"></div></a>

<div class="login-block">
    <h1>Welcome</h1>
   <p>Welcome to Mafia Town, the turn-based multiplayer role-playing game about lies, deception, and betrayal. Similar to the card game of the same name or similar games such as Werewolves, mafia is a game in which two sides (Mafia and Townspeople) must seek each other out and eliminate one another. Will you survive?</p>
</div>

<div class="login-block">
    <h1>Login to Play</h1>
    <input type="text" value="" placeholder="Username" id="username" />
    <input type="password" value="" placeholder="Password" id="password" />
    <button>Play</button>
   <p>Don't have an account? <a href="users/sign_up">Register here</a>.</p>
</div>

<div class="login-block">
    <h1>Roles</h1>
   <p>At the start of each round, each player is assigned a random role.<br>
         <font color="red"><b><u>Mafia</b></u><br>Vote who to kill each night<br></font>
         <font color="green"><b><u>Doctor</b></u><br>Choose someone to save each night<br></font>
          <font color="blue"><b><u>Detective</b></u><br>Investigate someone each night<br></font>
         <b><u>Townsperson</b></u><br>No night abilities, but can vote on suspected mafia during the day.</p></p>
</div>


</body>

</html>